// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc7127.LongmetalRobotics;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.PWMTalonSRX;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainSpeedController1;
    public static SpeedController driveTrainSpeedController3;
    public static SpeedControllerGroup driveTrainSpeedControllerGroup1;
    public static SpeedController driveTrainSpeedController4;
    public static SpeedController driveTrainSpeedController5;
    public static SpeedControllerGroup driveTrainSpeedControllerGroup2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainSpeedController1 = new PWMTalonSRX(0);
        LiveWindow.addActuator("DriveTrain", "Speed Controller 1", (PWMTalonSRX) driveTrainSpeedController1);
        driveTrainSpeedController1.setInverted(false);
        driveTrainSpeedController3 = new PWMTalonSRX(2);
        LiveWindow.addActuator("DriveTrain", "Speed Controller 3", (PWMTalonSRX) driveTrainSpeedController3);
        driveTrainSpeedController3.setInverted(false);
        driveTrainSpeedControllerGroup1 = new SpeedControllerGroup(driveTrainSpeedController1, driveTrainSpeedController3  );
        LiveWindow.addActuator("DriveTrain", "Speed Controller Group 1", driveTrainSpeedControllerGroup1);
        
        driveTrainSpeedController4 = new PWMTalonSRX(3);
        LiveWindow.addActuator("DriveTrain", "Speed Controller 4", (PWMTalonSRX) driveTrainSpeedController4);
        driveTrainSpeedController4.setInverted(false);
        driveTrainSpeedController5 = new PWMTalonSRX(4);
        LiveWindow.addActuator("DriveTrain", "Speed Controller 5", (PWMTalonSRX) driveTrainSpeedController5);
        driveTrainSpeedController5.setInverted(false);
        driveTrainSpeedControllerGroup2 = new SpeedControllerGroup(driveTrainSpeedController4, driveTrainSpeedController5  );
        LiveWindow.addActuator("DriveTrain", "Speed Controller Group 2", driveTrainSpeedControllerGroup2);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
